config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
    get '/members', to: 'members#index', as: 'members'
    post '/members', to: 'members#create'
    get '/members/new', to: 'members#new', as: 'new_member'
  end
  devise_for :users
  get 'product_home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'product_home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_user_relationships
  has_many :users, through: :project_user_relationships

  has_many :tasks
end

app/models/project_user_relationship.rb
class ProjectUserRelationship < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :project_user_relationships
  has_many :projects, through: :project_user_relationships

  has_many :tasks     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project

  def index
    @members = @project.users
  end

  def new
    @project_user_relationship = ProjectUserRelationship.new
  end

  def create
    @project_user_relationship = @project.project_user_relationships.new(relationship_params)
    if @project_user_relationship.save
      redirect_to project_path(@project)
    end
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end

    def relationship_params
      params.require(:project_user_relationship).permit(:user_id, :incharge)
    end
end

app/controllers/product_home_controller.rb
class ProductHomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        @project_user_relationship = current_user.project_user_relationships.new(project_id: @project.id, incharge: true)
        @project_user_relationship.save!
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :check_incharge, only: %i[new, edit, destroy]
  before_action :set_project
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = @project.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_path(@project, @task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def check_incharge
      puts(!@project.project_user_relationships.find_by_user_id(current_user.id).incharge)
      if !current_user && !@project.project_user_relationships.find_by_user_id(current_user.id).incharge
        redirect_to project_tasks_path(@project)
      end
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :description, :user_id, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/product_home_helper.rb
module ProductHomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container
    a.navbar-brand href="#"  Niyat
    button.navbar-toggler aria-controls="navbarNavDropdown" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarNavDropdown" data-toggle="collapse" type="button"
      span.navbar-toggler-icon
    #navbarNavDropdown.collapse.navbar-collapse
      ul.navbar-nav.ml-auto
        li.nav-item.active
          a.nav-link href="#"
            | Home
            span.sr-only (current)
        /li.nav-item
          a.nav-link href="#"  Features
        /li.nav-item
          a.nav-link href="#"  Pricing
        li
          - if user_signed_in?
            = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link'
          - else
            = link_to 'Log In', new_user_session_path, class: 'nav-link'
            li
              = link_to 'Sign Up', new_user_registration_path, class: 'nav-link'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManagePro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'  %>
    <%= yield %>
  </body>
</html>

app/views/members/index.html.slim
.container
  h1 Members in #{@project.name}
  table.table
    thead
      tr
        th Name
        th Email
    tbody
    - @project.users.each do |user|
      tr
        td = user.name
        td = user.email

app/views/members/new.html.slim
.container
  = form_for(@project_user_relationship, url: project_members_path, method: :post) do |f|
    - if @project_user_relationship.errors.any?
      #error-explanation
        ul
          - @project_user_relationship.errors.each do |message|
            li = message

    .field.mb-3
      = f.label :user
      = f.select :user_id, (User.all - @project.users).collect { |u| [u.name, u.id] }, { required: true }, class: 'form-control'

    .field.mb-3
      = f.label :incharge
      = f.select :incharge, [true, false], {}, class: "form-control"

    .actions
      = f.submit "Add User", class: "btn btn-primary"

app/views/product_home/index.html.slim
.container
  h1 Welcome to manage pro

app/views/projects/_form.html.slim
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - @project.errors.full_messages.each do |message|
          li = message

  .field.mb-3
    = f.label :name
    = f.text_field :name, class: "form-control"
  .field.mb-3
    = f.label :description
    = f.text_area :description, class: "form-control"
  .actions = f.submit

app/views/projects/edit.html.slim
.container
  h1 Editing project

  == render 'form'

  => link_to 'Show', @project
  '|
  =< link_to 'Back', projects_path

app/views/projects/index.html.slim
.container
  h1 Listing projects

  table.table
    thead
      tr
        th Name
        th Description
        th
        th
        th

    tbody
      - @projects.each do |project|
        tr
          td = project.name
          td = project.description
          td = link_to 'Show', project
          td = link_to 'Edit', edit_project_path(project)
          td = link_to 'Destroy', project, data: { confirm: 'Are you sure?' }, method: :delete

  br

  = link_to 'New Project', new_project_path

app/views/projects/new.html.slim
.container
  h1 New project

  == render 'form'

  = link_to 'Back', projects_path

app/views/projects/show.html.slim
.container
  p#notice = notice

  p
    strong Name:
    = @project.name
  p
    strong Description:
    = @project.description

  .row
    .col.col-6.col-sm-6.col-md-6.col-lg-6
        h1 Members in #{@project.name}
        table.table
          thead
            tr
              th Name
              th Email
          tbody
          - @project.users.each do |user|
            tr
              td = user.name
              td = user.email
        = link_to "New member", project_new_member_path(@project), class: "btn btn-success"
    .col.col-6.col-sm-6.col-md-6.col-lg-6
        h1 Listing tasks for #{@project.name}

        table.table
          thead
            tr
              th Name
              th Description
              th User
              th
              th
              th

          tbody
            - @project.tasks.each do |task|
              tr
                td = task.name
                td = task.description
                td = task.user.name
                td = link_to 'Show', project_task_path(@project, task)
                td = link_to 'Edit', edit_project_task_path(@project, task)
                td = link_to 'Destroy', project_task_path(@project, task), data: { confirm: 'Are you sure?' }, method: :delete
        = link_to "New Task", new_project_task_path(@project), class: "btn btn-success"

  .mt-4
    => link_to 'Edit', edit_project_path(@project)
    '|
    =< link_to 'Back', projects_path

app/views/tasks/_form.html.slim
= form_for [@project, @task] do |f|
  - if @task.errors.any?
    #error_explanation
      h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @task.errors.full_messages.each do |message|
          li = message

  .field.mb-3
    = f.label :name
    = f.text_field :name, class: "form-control"
  .field.mb-3
    = f.label :description
    = f.text_area :description, class: "form-control"
  .field.mb-3
    = f.label :user_id
    = f.select :user_id, @project.users.collect { |u| [u.name, u.id] }, {}, class: "form-control"

  .actions = f.submit class: "btn btn-primary"

app/views/tasks/edit.html.slim
.container
  h1 Editing task

  == render 'form'

  => link_to 'Show', project_task_path(@project, @task)
  '|
  =< link_to 'Back', project_tasks_path(@project)

app/views/tasks/index.html.slim
.container
  h1 Listing tasks for #{@project.name}

  table.table
    thead
      tr
        th Name
        th Description
        th User
        th
        th
        th

    tbody
      - @tasks.each do |task|
        tr
          td = task.name
          td = task.description
          td = task.user.name
          td = link_to 'Show', project_task_path(@project, task)
          td = link_to 'Edit', edit_project_task_path(@project, task)
          td = link_to 'Destroy', project_task_path(@project, task), data: { confirm: 'Are you sure?' }, method: :delete

  br

  = link_to 'New Task', new_project_task_path(@project)

app/views/tasks/new.html.slim
.container
  h1 New task

  == render 'form'

  = link_to 'Back', project_tasks_path(@project)

app/views/tasks/show.html.slim
.container
  p#notice = notice

  p
    strong Name:
    = @task.name
  p
    strong Description:
    = @task.description
  p
    strong User:
    = @task.user_id
  p
    strong Project:
    = @task.project_id

  => link_to 'Edit', edit_project_task_path(@project, @task)
  '|
  =< link_to 'Back', project_tasks_path(@project)

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>